openai:
  api_key: "YOUR-OPENAI-API-KEY"
  model: "gpt-4o" 
  max_retries: 7

processing:
  # These represent the headings in a docx delimiting a section that will be sent for review or translation
  heading_styles: 
    - "Heading 1"
    - "Heading 2"
    - "Title"
  min_word_threshold: 2
  # True: section title will be appended to result. False: output will have result only
  add_section_title: true
  
  # Possible processors (can be overridden by CLI --processor):
  # - Reviewer: Default grammar and style reviewer.
  # - ScientificReviewer: Specialized reviewer focusing on verifying scientific content.
  # - Translator: Translates from source_lang to target_lang.
  # - Reporter: Generates informational summaries. No AI required.
  # - CustomPromptProcessor: Processes the docuemnt vai any prompt that's defined via CLI.
  processor: "Reviewer"

io:
  input_directory: "./input_docs"
  output_directory: "./outputs"
  supported_extensions: [".docx", ".txt", ".md", ".pdf"]

logging:
  level: "INFO"
